CREATE TABLE TOUR_PACKAGE (
    id   NUMERIC(32)   PRIMARY KEY,
    code VARCHAR(255)  UNIQUE NOT NULL,
    name VARCHAR(255)  UNIQUE NOT NULL
);
CREATE SEQUENCE TOUR_PACKAGE_SEQ START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX TOUR_PACKAGE_CODE_IDX ON TOUR_PACKAGE(code);
CREATE UNIQUE INDEX TOUR_PACKAGE_NAME_IDX ON TOUR_PACKAGE(name);


CREATE TABLE TOUR (
    id          NUMERIC(32)     PRIMARY KEY,
    code        VARCHAR(255)    UNIQUE NOT NULL,
    name        VARCHAR(255)    UNIQUE NOT NULL,
    description VARCHAR(1024)   NOT NULL,
    difficulty  VARCHAR(50)     NOT NULL,
    region      VARCHAR(50)     NOT NULL,
    tour_package_id NUMERIC(32) NOT NULL,
    CONSTRAINT TOUR_TOUR_PACKAGE_ID_FK FOREIGN KEY (tour_package_id) REFERENCES TOUR_PACKAGE(ID)
);
CREATE SEQUENCE TOUR_SEQ START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX TOUR_CODE_IDX ON TOUR(code);
CREATE UNIQUE INDEX TOUR_NAME_IDX ON TOUR(name);
CREATE UNIQUE INDEX TOUR_TOUR_PACKAGE_ID_IDX ON TOUR(tour_package_id);

CREATE TABLE CLIENT (
    id         NUMERIC(32)       PRIMARY KEY,
    first_name VARCHAR(128)      NOT NULL,
    last_name  VARCHAR(128)      NOT NULL,
    email      VARCHAR(128)      NOT NULL
);
CREATE SEQUENCE CLIENT_SEQ START WITH 1 INCREMENT BY 1;


CREATE TABLE TOUR_RATING (
    id        NUMERIC(32)       PRIMARY KEY,
    tour_id   NUMERIC(32)       NOT NULL,
    client_id NUMERIC(32)       NOT NULL,
    comment   VARCHAR(1024)     NOT NULL,
    score     NUMERIC(10)       NOT NULL,
    CONSTRAINT TOUR_RATING_TOUR_ID_FK FOREIGN KEY (tour_id) REFERENCES TOUR(id),
    CONSTRAINT TOUR_RATING_CLIENT_ID_FK FOREIGN KEY (client_id) REFERENCES CLIENT(id)
);
CREATE SEQUENCE TOUR_RATING_SEQ START WITH 1 INCREMENT BY 1;

