spring:
  application:
    name: springbootimages
  mongodb:
    uri: mongodb://root:password@localhost:27017/?tls=true
    database: images
  data:
    rest:
      base-path: "/api/v1/datarest/"
  rabbitmq:
    host: localhost
    port: 5671
    username: myuser
    password: secret
    ssl:
      enabled: true
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: "springbootimages"
          keystore:
            location: "classpath:keystore.p12"
            password: "password"
            type: "PKCS12"
        client:
          truststore:
            certificate: "classpath:truststore.p12"
            password: "password"

server:
  port: 8081
  ssl:
    bundle: server


management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,cache,prometheus
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    env:
      enabled: true

info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
