listeners.tcp = none

listeners.ssl.default = 5671

ssl_options.cacertfile = /etc/rabbitmq/tls/ca.crt
ssl_options.certfile   = /etc/rabbitmq/tls/server.crt
ssl_options.keyfile    = /etc/rabbitmq/tls/server.key

ssl_options.verify = verify_none
ssl_options.fail_if_no_peer_cert = false


# Management UI

management.ssl.port = 15671

management.ssl.cacertfile = /etc/rabbitmq/tls/ca.crt
management.ssl.certfile   = /etc/rabbitmq/tls/server.crt
management.ssl.keyfile    = /etc/rabbitmq/tls/server.key

management.ssl.verify     = verify_none
management.ssl.fail_if_no_peer_cert = false


# Prometheus plugin
prometheus.tcp.listener = none

prometheus.ssl.port = 15691

prometheus.ssl.cacertfile = /etc/rabbitmq/tls/ca.crt
prometheus.ssl.certfile   = /etc/rabbitmq/tls/server.crt
prometheus.ssl.keyfile    = /etc/rabbitmq/tls/server.key

prometheus.ssl.verify     = verify_none
prometheus.ssl.fail_if_no_peer_cert = false


# Logging
log.console = true
log.console.level = info
